import {
  Users,
  Home,
  FolderOpen,
  AlignJustify,
  Circle,
  SearchX,
  BookOpen,
  Calendar,
  Star,
  Settings,
  User,
  LogIn,
  Search,
  Plus,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  Check,
  Sun,
  Moon,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudSun,
  CloudMoon,
  CloudFog,
  Wind,
  Thermometer,
  RefreshCw,
  Download,
  Upload,
  Trash2,
  Edit3,
  Eye,
  EyeOff,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  FileText,
  Clipboard,
  Target,
  TrendingUp,
  Flame,
  Zap,
  Award,
  BarChart3,
  PieChart,
  Activity,
  Shield,
  AlertTriangle,
  Info,
  CheckCircle2,
  XCircle,
  HelpCircle,
  Loader2,
  Copy,
  Move,
  Grid,
  List,
  Filter,
  Bookmark,
  PenLine,
  Calculator,
  Timer,
  GraduationCap,
  Brain,
  Sparkles,
  Coffee,
  MapPin,
  Play,
  Pause,
  Flag,
  RotateCcw,
  NotebookPen,
  KeyRound,
  Inbox,
  LogOut,
  Database,
} from "lucide-react";

const iconMap = {
  home: Home,
  folder: FolderOpen,
  folderOpen: FolderOpen,
  book: BookOpen,
  bookOpen: BookOpen,
  calendar: Calendar,
  star: Star,
  settings: Settings,
  user: User,
  login: LogIn,
  search: Search,
  searchX: SearchX,
  alignJustify: AlignJustify,
  circle: Circle,
  arrowBack: ArrowLeft,
  plus: Plus,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  close: X,
  check: Check,
  sun: Sun,
  moon: Moon,
  clock: Clock,
  cloud: Cloud,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudLightning: CloudLightning,
  cloudSun: CloudSun,
  cloudMoon: CloudMoon,
  cloudFog: CloudFog,
  wind: Wind,
  thermometer: Thermometer,
  refresh: RefreshCw,
  download: Download,
  upload: Upload,
  trash: Trash2,
  edit: Edit3,
  eye: Eye,
  eyeOff: EyeOff,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  moreHorizontal: MoreHorizontal,
  file: FileText,
  fileText: FileText,
  clipboard: Clipboard,
  target: Target,
  trending: TrendingUp,
  trendingUp: TrendingUp,
  flame: Flame,
  zap: Zap,
  award: Award,
  barChart: BarChart3,
  pieChart: PieChart,
  activity: Activity,
  shield: Shield,
  alertTriangle: AlertTriangle,
  info: Info,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  helpCircle: HelpCircle,
  loader: Loader2,
  copy: Copy,
  move: Move,
  grid: Grid,
  list: List,
  filter: Filter,
  bookmark: Bookmark,
  pen: PenLine,
  penLine: PenLine,
  calculator: Calculator,
  users: Users,
  timer: Timer,
  graduation: GraduationCap,
  brain: Brain,
  sparkles: Sparkles,
  coffee: Coffee,
  mapPin: MapPin,
  play: Play,
  pause: Pause,
  flag: Flag,
  retake: RotateCcw,
  rotateCcw: RotateCcw,
  notebook: NotebookPen,
  notebookPen: NotebookPen,
  key: KeyRound,
  keyRound: KeyRound,
  inbox: Inbox,
  logout: LogOut,
  database: Database,
};

export default function Icon({
  name,
  size = 18,
  className = "",
  strokeWidth = 2,
  ...props
}) {
  const LucideIcon = iconMap[name];

  if (!LucideIcon) {
    return null;
  }

  return (
    <LucideIcon
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      {...props}
    />
  );
}
